name: autotrader-price
channels: [conda-forge]
dependencies:
  - python=3.10
  - scikit-learn=1.3.2
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - category_encoders
  - shap=0.44.1
  - pyyaml
  - notebook
  - streamlit
  - pip    
